### ISSUE TITLE
Rethink Entrypoint

### ISSUE THREAD

**Issue by ColonelPanicks** [openflighthpc/flight-cloud#204]
Originally there was one entrypoint, `bin/cloud`, but the need for a cleaner split (#137) between platforms has lead us to `bin/cloud-{aws,azure}`.

While I think that a clear separation between platforms is needed (rather than being implicitly determined from the config file) I also find that having two entrypoints is a little bulky and inflexible (especially when additional cloud providers are supported). 

My proposal is that the platform is sub-commanded off of cloud so:
```
# Run AWS command
bin/cloud aws list deployments

# Run Azure command
bin/cloud azure list deployments
```

The usage of a single entrypoint also eases integration with [Flight Runway](https://github.com/openflighthpc/flight-runway).

What are your thoughts on this?

**Comment by WilliamMcCumstie** [comment]
I don't think sub-commanding it in this way will resolve the bulkiness. It will make it impossible to completely separate the `aws` and `azure` tools as they will need to share the same CLI file.

Also our version of commander only properly supports 2 levels of (sub)commnads. Whilst this issue could be resolved, it would be a bit of work for little gain.

Instead have you tried:
```
export CLOUDWARE_PROVIDER=...
bin/cloud --help
```

This amounts to the same thing you proposed, but without the headaches that subcommands introduces. It also should work out of the box
