### ISSUE TITLE
Change Templates into Nodes

### ISSUE THREAD

**Issue by ColonelPanicks** [openflighthpc/flight-cloud#221]
Currently, imported cloud files are considered generic templates in cloudware.

Going forward, it would be useful if cloudware understands what a node/group/domain is and can import these files directly into configured nodes. 

The thinking behind this would be for supporting `edit` commands (#220)

**Comment by WilliamMcCumstie** [comment]
This is going to be part of a long term improvement cloudware project. In essence this has already been completed by the introduction of `Models::Node` and `Models::Group`. Their is still some internal refactoring that will need to be done
