### ISSUE TITLE
Loosen 'domain' concept

### ISSUE THREAD

**Issue by ColonelPanicks** [openflighthpc/flight-cloud#258]
To provide greater flexibility to cloud usage the idea of a domain should not be:
1. Restricted to one per cluster
2. Automatically created (#254)
3. Referred to as `domain`

I propose that there should be `node` and `non-node` concepts in `flight-cloud` so that `domain` and any other cloud templates that don't include instance resources (so no power command support, etc) can be used as generic resources.

Note: Happy to call it something else other than `non-node`.

**Comment by WilliamMcCumstie** [comment]
My vote is to call them a `node` or `resource`

**Comment by WilliamMcCumstie** [comment]
It might be possible to make the distinction implicit. In order for the power commands to work, they need a "machine id" returned from the provider.

Therefore if you try and power a "deployment" without the ID, then it should error. "Can not power a non node resource".

By making it implicit, the user won't have to worry about the type of deployment. It will also reduce the duplication in the CLI and internals.

Whilst a node or non-node is offline, the distinction is reasonably arbitrary. However it won't be possible to list the offline nodes only, as nodes can only be identified once deployed

**Comment by ColonelPanicks** [comment]
> Therefore if you try and power a "deployment" without the ID, then it should error. "Can not power a non node resource".

Yep, agreed, this is almost word-for-word something I suggested to @atoghill yesterday.

I think that, with us trying to step away from "just a bunch of templates", the resource objects have been restricted too much in favour of the usage examples. 

Ultimately, where I think we went wrong is thinking that a `node` needs to be a sort of special object. When in fact, all we want is for **a template to be treated as a single resource entity with metadata** and for additional node-based helper commands (like power) to work if particular information is provided.

> Whilst a node or non-node is offline, the distinction is reasonably arbitrary. However it won't be possible to list the offline nodes only, as nodes can only be identified once deployed.

True, it would be handy to know the nodes pre-deployment.

We could get a little bit more identification of nodes by possibly:
- Having a `create` flag (`-n`?) to mark the template object as "containing a node"  (or even just default to that and flag non-node objects)
- Having separate `create` commands (`create-node` and `create-resource`)
- Implicit "node recognition" from metadata (it has groups, it's a node!)
- Implicit "node recognition" from template output tags (it has ID, it's a node!)

**Comment by WilliamMcCumstie** [comment]
This issue has been a major driving force towards version `2.0.0+`. The concept of a `domain` has been refined down to a top level deployment. The more general term `cluster` now refers more to a profile of domain/groups/nodes. The `domain` deployment will have a full CRUD stack.

It is no longer possible to define the "domain and all the nodes" within a single template. Therefore the "implicit node recognition" is no longer required. If the additional functionality is required, then a new issue should be created.
