### ISSUE TITLE
No way of editing parameters

### ISSUE THREAD

**Issue by ColonelPanicks** [openflighthpc/flight-cloud#262]
Currently, parameters are parsed at `create` time. When these values are filled there is no way through cloud to change the values of these parameters.

There should be an `edit-parameters` command or something that will allow for changing the metadata for a template as the current `edit` only modifies the template.

Related to #256

**Comment by WilliamMcCumstie** [comment]
So the current `edit` command does allow updating parameters, but only if they where previously missing.

My recommendation is to prompt for all the parameters, but default to the previous value. There is internal code to do this already. It just needs to be hooked into the cli.

I don't believe a separate `edit-parameter` command is required. Instead possible a `--parameters-only` flag (or similar) instead

**Comment by ColonelPanicks** [comment]
Personally, I find that having to go through the edit command to change parameters adds more steps to the deployment process than previous versions of cloud.

I'd opt for supporting parameter substitution at `deploy` like with the previous versions of cloud (either prompt for missing or CLI args to fill them). Not to say that the ability to edit parameters would be nullified, there's definitely a case for modifying them. 

How I'd want this to work is:

1. Parameters should _not_ be prompted for at `create`
2. Parameters should _not_ be prompted for at `edit` (but _can_ be edited either via an edit flag or a separate edit command)
3. Parameters can be set at `deploy` with `-p 'parameter=value'`
    a. This should also overwrite existing values for parameters if they already have values
4. Parameters can be set at `deploy` via prompts (for any currently empty parameters)

As for handling unused/removed parameters, I'd think it's not that much to worry about. If there's a decent interactive way of editing parameters (open up a list of the parameter key/val pairs in an editor) then a user can remove them if they deem it necessary.

**Comment by atoghill** [comment]
Based on the above comment this issue can be marked as resolved as of #263.
