### ISSUE TITLE
Don't prompt for editor

### ISSUE THREAD

**Issue by ColonelPanicks** [openflighthpc/flight-cloud#273]
Prompting for an editor provides an unnecessary extra step when running `create`/`edit`. Instead:
- Use the `EDITOR` environment variable
- Default to using `vim` if EDITOR not set

**Comment by WilliamMcCumstie** [comment]
`TTY::Config` already obeys `$VISUAL` and `$EDITOR`. As `vim` isn't always installed, the default should be `vi`. As know one what's that, we should keep the prompt.
